### ISSUE TITLE
The cert no longer exists

### ISSUE THREAD

**Issue by Bam92** [elharony/google-mobile-web-specialist-certification-guide#4]
It seems that Google has ended with this program. Last year I had a scholarship with Google Africa, Andela, and Pluralsight but they told us that "there's no cert this year".

**Comment by karakunai** [comment]
It seems like Google haven't update the page yet, the links are no longer accessible therefore it'd be better to highlight the change on `README.md`. We can still keep this repo though :)

**Comment by elharony** [comment]
Thank you @Bam92 , @ronanharris09. I've added an update to the repo that - unfortunately - this certification no longer exists.
